### ISSUE TITLE
Installing on py37 gives error AttributeError: type object 'Callable' has no attribute '_abc_registry'

### ISSUE THREAD

**Issue by chauhang** [facebookresearch/dynalab#73]
On running `pip install -e .`  in python 3.7 environment getting error: 

"AttributeError: type object 'Callable' has no attribute '_abc_registry'"

Workaround for this has been described at https://stackoverflow.com/questions/55833509/attributeerror-type-object-callable-has-no-attribute-abc-registry

Removing typing by running `pip uninstall typing` worked on Ubuntu 18.04 python 3.7 conda environment

**Comment by mazhiyi** [comment]
Hi @chauhang, thanks for raising this! I don't have immediate access to a Ubuntu 18.04 python 3.7 conda environment, and I've tried the following as the closest proxy. Unfortunately I'm not able to reproduce this error on my side. 

1. On a Ubuntu 20.04, I created a fresh conda env with python 3.7 and run `pip install -e .`. I successfully installed dynalab without seeing this error. 

2. On a Ubuntu 18.04 with python 3.7 but not access to conda, I tried both `pip install -e .` and `python -m pip install -e .` (to make sure the correct pip version was used). I successfully installed dynalab in both cases. 

3. On my MacOS, I installed a fresh conda env with python 3.7 and run `pip install -e .`. I successfully installed dynalab without seeing this error. (This is closest setup to the post you linked).

I wonder if you could give a bit more info on how to reproduce this, and maybe show a bit more trace here so we can also see exactly from which dependency typing is imported?

**Comment by mazhiyi** [comment]
Closing this for inactivity. Please reopen if the issue is not resolved. Thanks!
